### ISSUE TITLE
Tutorial example code needed slight adjustment

### ISSUE THREAD

**Issue by jconti** [slagyr/joodo#17]
I'm walking through the tutorial (very nice).  This evening I made some small adjustments to the source to get it to run.  On page http://www.joodoweb.com/tutorial/views:

``` clojure
(ns sample_app.view.view-helpers-spec
  (:require [speclj.core :only (describe it should= run-specs around with)]
            [joodo.datetime :only (parse-datetime)]
            [sample_app.view.view-helpers :refer [get-post-name get-post-date
                                                  order-posts]]))
```

needed to be changed to be:

``` clojure
(ns sample-app.view.view-helpers-spec
  (:require [speclj.core :refer (describe it should= run-specs around with)]
            [chee.datetime :refer (parse-datetime)]
            [sample-app.view.view-helpers :refer [get-post-name get-post-date order-posts]]))
```

**Comment by jconti** [comment]
Forgot to add some details.  Clojure is 1.4 and Lein/Java is:

``` bash
bash-3.2$ lein version
Leiningen 2.0.0-preview10 on Java 1.6.0_37 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by slagyr** [comment]
Ah thanks!  I've fixed the mistake and redeployed.

**Comment by jconti** [comment]
Thanks.  Enjoying the code so far.  Much appreciated!

**Comment by jconti** [comment]
PS: Just noticed you have the joodoweb source here on github.  Seems like that would have been a better place to suggest, so I will in the future.  Thanks again.
