### ISSUE TITLE
Could use a function in datetime that rounds to nearest midnight (via floor).

### ISSUE THREAD

**Issue by sdegutis** [slagyr/joodo#26]
So that calling `(round (now))` any time today will always give me `(datetime 2013 10 05 0 0 0)`. I'm about to write that fn in an app, but maybe it'd be nice to have in this lib?

**Comment by slagyr** [comment]
There could be a whole series of fns.. (round-to-nearest-minute) (round-to-nearest-hour) (round-to-nearest-day) etc…

**Comment by sdegutis** [comment]
Or how about (round t period) ?

**Comment by sdegutis** [comment]
Or better yet, `(round time period direction)` where period can be anything in `[:minute :hour :day :month :year]` and direction must be one of `[:up :down :closest]`?
