### ISSUE TITLE
lein-joodo dependency on lein 2 preview 7

### ISSUE THREAD

**Issue by trptcolin** [slagyr/joodo#9]
Is there a reason lein-joodo actually needs this dependency to be required in project.clj? Everything still seems to work fine when I remove it, and leaving it in has the potential for strange conflicts if the person running `lein joodo` is on a different version of leiningen. I'm happy to make a pull request if removing it is OK.

**Comment by slagyr** [comment]
Leaving lein-joodo as a dependency is a convenience.  Say developer #1 installed the lien-joodo plugin, creates a project, and checks it into source control.  When developer #2 checkout the project, all the lein commands will work for him so long as lein-joodo is in the project.   But that's lein1.

This should be rethought with lein2.

**Comment by trptcolin** [comment]
Sorry, to be more specific: I don't understand why this line is required: 

https://github.com/slagyr/joodo/blob/master/lein-joodo/project.clj#L17

We can also just talk about this in person if I'm misunderstanding something.
